language: julia
os:
- linux
julia:
- 1.1
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaPackaging/BinaryProvider.jl"))'
- julia -e 'using Pkg; Pkg.add("BinaryBuilder.jl");
  Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: "eed/s1byI7+On3gYaJv0ssfxVoljvVpQKuxiFc1PHNfAOQ1p7Li3cpppeC6ic5WVskm301NICKLMkV/6DU3m58Y1xX7QLVqQ1hzzIjoNvX8SVBolCpmgYqlpsqa0mUU5PdTrKi1NhR/46dt3FJrlCnuByMBrd4xUOGjp7hkPgwZ4fXpDXPCb6gLqkYsKdhRS8fBfJFwGn/2xhChs2SheZ9iTaAyJDZHKFuSDfrsHHNDatYt138N0vw9NiRQ7Rrx7euupXi6S2pTsCkHhi+yAmslKdPbzoDXdPCLjDtbRSGVLBv6VNk0rb/IpmI86Z2LyRL5RZZz9HxMcVP6J9h02SVIG9y/V7ZaUDW3esut0uey6IuWBJ7LHNBE8sRXOADhOfkrPqxOp8XYT9+4R5dkHCUS/sNH5GzJy8XtKTOwZKAqL1axNU2AGa8ksYGqXv2iwYAnwHaCceGWbXRpy88aBrkytIHUFzuOhdO/NIgD3hmR5jhlF88HDjgeUQma0g4hIdCT/2CvWZijMct/OOHg5SKeoyx4ci1AT9qWC3qWqn/bRhw+5OfQj4RsN7T3jvGYZmsjLhSPrlNC1QKkAPBJ4gUeTnSdeZ6wRd8wgnWBxGPH7s7FokH6xCZCJeLtjWU4rjO03fvPJeQyEGmxK4AgbuSBJLOLpIVeaQRFIl8t+TbY="
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: JiazhengZhu/SDPABuilder
    tags: true
